version: '3.4'

services:
  db:
    image: postgres:14.2-alpine
    container_name: personality-quiz-postgres
    volumes:
      - db:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: redis:alpine3.8
    container_name: personality-quiz-redis
    mem_limit: 256m
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "6379:6379"
    restart: on-failure
    logging:
      driver: none

  ruby:
    build: .
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - CHROME_URL=http://chrome:3333
    container_name: personality-quiz-ruby
    working_dir: /rails
    restart: always
    tty: true
    volumes:
      - .:/rails
      - app-storage:/rails/storage
    ports:
      - "3000:3000"

  chrome:
    image: browserless/chrome:latest
    ports:
      - 3333:3333
    # Mount application source code to support file uploading
    # (otherwise Chrome won't be able to find files).
    # NOTE: Make sure you use absolute paths in `#attach_file`.
    volumes:
      - .:/app:cached # change it for your rails' container directory
    environment:
      # By default, it uses 3000, which is typically used by Rails.
      PORT: 3333
      # Set connection timeout to avoid timeout exception during debugging
      # https://docs.browserless.io/docs/docker.html#connection-timeout
      CONNECTION_TIMEOUT: 600000

volumes:
  db: {}
  redis-data: {}
  app-storage: {}

networks:
  default:
    name: personality-quiz
